USE DATABASE SNOWFLAKE_SAMPLE_DATA;

DESC TABLE TPCDS_SF100TCL.STORE_SALES;

SELECT COUNT(*)
FROM TPCDS_SF100TCL.STORE_SALES;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE SCHEMA IF NOT EXISTS BRONZE;

--Phase-2 Raw data ingestion
CREATE OR REPLACE TABLE BRONZE.STORE_SALES_RAW AS 
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES
LIMIT 50000000;

--Phase-3 Data validation (completeness)
SELECT COUNT(*) FROM BRONZE.STORE_SALES_RAW;

SELECT COUNT(*) 
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES;

DESC TABLE BRONZE.STORE_SALES_RAW;

SELECT 
COUNT(*) AS total_rows,
COUNT(ss_sales_price) AS non_null_sales_price
FROM BRONZE.STORE_SALES_RAW;

--OPTIONAL
SELECT MIN(ss_sold_date_sk), MAX(ss_sold_date_sk)
FROM BRONZE.STORE_SALES_RAW;
