USE WAREHOUSE COMPUTE_WH;

USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE OR REPLACE TABLE SILVER.STORE_SALES_CLEAN AS 
SELECT 
    ss.ss_sold_date_sk,
    ss.ss_store_sk,
    ss.ss_customer_sk,
    ss.ss_quantity,
    ss.ss_sales_price
FROM BRONZE.STORE_SALES_RAW ss
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.DATE_DIM d
    ON ss.ss_sold_date_sk = d.d_date_sk
WHERE d.d_year BETWEEN 1998 AND 1999
AND ss.ss_sales_price IS NOT NULL
AND ss.ss_quantity > 0;

DESC TABLE SILVER.STORE_SALES_CLEAN;

SELECT MIN(ss_sales_price), MAX(ss_sales_price)
FROM SILVER.STORE_SALES_CLEAN;

--Validation through row count
SELECT COUNT(*) FROM BRONZE.STORE_SALES_RAW;
SELECT COUNT(*) FROM SILVER.STORE_SALES_CLEAN;

--Null Check
SELECT COUNT(*)
FROM SILVER.STORE_SALES_CLEAN
WHERE ss_sales_price IS NULL;

--Negative Check
SELECT COUNT(*)
FROM SILVER.STORE_SALES_CLEAN
WHERE ss_quantity <= 0;

